### ISSUE TITLE
Recordings - It is not possible to play the whole session

### ISSUE THREAD

**Issue by SenNeonoveNoci** [smartlook/UnityPackage#1]
Organization: [538482](https://fiona.smartlook.com/admin/organization/538482)

Platform: Android

SDK version: 1.8.7-unity

[Preview](https://app.smartlook.com/play/shared/c7006f36e0b078d5820e162917faa22558a76d37)

Issue: it is not possible to play the whole session, once you reach 7 minutes of playback, the session ends. The length is over 40 minutes.

Convo [here](https://app.intercom.com/a/apps/x8uma9tn/inbox/inbox/5741392/conversations/128056700470930).

**Comment by js-supp** [comment]
I am writing to them to give new unity package a go, as from the previous conversation I understood it should help.

**Comment by js-supp** [comment]
no reply, closing

**Comment by lucianocheng** [comment]
Also seeing this issue. Unable to play whole session past the first few seconds.
