### ISSUE TITLE
Duplicate classes when building

### ISSUE THREAD

**Issue by SenNeonoveNoci** [smartlook/UnityPackage#2]
**customer**: [530989](https://fiona.smartlook.com/admin/organization/530989)
**platfrom**: Android
**tech**: Unity
**version**: `com.smartlook.recording:app:1.8.7-unity-lite-support`

**issue**: facing duplicate class error when we use both Google Firebase SDKs and Smartlook SDKs in our Unity project. APK builds successfully without Google Firebase SDK using only Smartlook SDK.

The error that we are facing is - Execution failed for task ':launcher:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
> Duplicate class a.a.a.a found in modules jetified-app-1.8.7-unity-lite-support-runtime (com.smartlook.recording:app:1.8.7-unity-lite-support) and jetified-app-1.8.7-unity-support-runtime (:app-1.8.7-unity-support:)

![Image](https://user-images.githubusercontent.com/43814366/211279746-a9ad747a-f2da-4123-ae4b-5de6b9ef658f.png)

**Comment by js-supp** [comment]
I linked them the new unity package as it seems it should fix the issue.

**Comment by js-supp** [comment]
no reply from the customer, closing.
