### ISSUE TITLE
Errors when PlayerSettings are in WebGL

### ISSUE THREAD

**Issue by nosirrahh** [smartlook/UnityPackage#3]
When the PlayerSettings of the project is set to WebGL we get this errors:

Assets\Smartlook\SmartlookAnalytics\Scripts\Smartlook.cs(317,56): error CS0246: The type or namespace name 'IntegrationListener' could not be found (are you missing a using directive or an assembly reference?)

Assets\Smartlook\SmartlookAnalytics\Scripts\Smartlook.cs(451,65): error CS0246: The type or namespace name 'IntegrationListener' could not be found (are you missing a using directive or an assembly reference?)

<img width="539" alt="image" src="https://user-images.githubusercontent.com/28313335/223448807-b4ca33a6-888d-4626-af69-683a308acc0d.png">

<img width="542" alt="image" src="https://user-images.githubusercontent.com/28313335/223448891-3412635f-01dd-4b9e-b2fe-fd857379f95a.png">

**Comment by MichalZSmartLook** [comment]
Fixed in Unity Package version 1.1. 
It will not show error neither cause build issue.
Please take note that Smartlook Unity package supports only Android and iOS and it does not work on any other platform.
